openapi: 3.0.0
info:
  title: Autorizador API
  description: API para autorização de transações e gerenciamento de cartões
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /cartoes:
    post:
      summary: Cria um novo cartão
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartaoRecord'
      responses:
        '201':
          description: Cartão criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartaoRecord'
        '422':
          description: Cartão já existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartaoRecord'

  /cartoes/{numeroCartao}:
    get:
      summary: Busca o saldo de um cartão
      parameters:
        - name: numeroCartao
          in: path
          required: true
          schema:
            type: string
            minLength: 16
            maxLength: 16
      responses:
        '200':
          description: Saldo retornado com sucesso
          content:
            application/json:
              schema:
                type: number
                format: double
        '404':
          description: Cartão não encontrado

  /transacoes:
    post:
      summary: Autoriza uma transação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoRecord'
      responses:
        '201':
          description: Transação autorizada com sucesso
          content:
            application/json:
              schema:
                type: string
        '422':
          description: Erro na transação
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    CartaoRecord:
      type: object
      properties:
        numeroCartao:
          type: string
          example: "1616161616161616"
        senha:
          type: string
          example: "4444"
      required:
        - numeroCartao
        - senha

    TransacaoRecord:
      type: object
      properties:
        numeroCartao:
          type: string
          example: "1616161616161616"
        valor:
          type: number
          format: double
          example: 100.00
        senha:
          type: string
          example: "4444"
      required:
        - numeroCartao
        - valor
        - senha
